name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c贸digo fuente
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Cambia esto si usas otra versi贸n de Node.js
          cache: 'npm'

      # 3. Instalar dependencias
      - name: Install dependencies
        env:
          CI: false
        run: npm install

      # 4. Lint y construcci贸n (Ignorar advertencias de ESLint)
      - name: Lint and Build
        env:
          CI: false
        run: |
          # Permite advertencias en ESLint
          npx eslint src --max-warnings=0 || true
          # Construye la aplicaci贸n incluso con advertencias
          npm run build

      # 5. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
